### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by smilesn** [rafael-carvalho/meraki-azure-ad#8]
After succeed login, captive portal return to internal server error.
Found this error, please help

2021-02-12T04:12:00.355757+00:00 app[web.1]: TypeError: Cannot read property 'indexOf' of undefined
2021-02-12T04:12:00.355758+00:00 app[web.1]: at ServerResponse.res.location (/app/node_modules/express/lib/response.js:711:13)
2021-02-12T04:12:00.355758+00:00 app[web.1]: at ServerResponse.res.redirect (/app/node_modules/express/lib/response.js:764:8)
2021-02-12T04:12:00.355759+00:00 app[web.1]: at /app/app.js:269:9
2021-02-12T04:12:00.355760+00:00 app[web.1]: at callbacks (/app/node_modules/express/lib/router/index.js:164:37)
2021-02-12T04:12:00.355760+00:00 app[web.1]: at complete (/app/node_modules/passport/lib/middleware/authenticate.js:263:13)
2021-02-12T04:12:00.355760+00:00 app[web.1]: at /app/node_modules/passport/lib/middleware/authenticate.js:270:15
2021-02-12T04:12:00.355761+00:00 app[web.1]: at pass (/app/node_modules/passport/lib/authenticator.js:431:14)
2021-02-12T04:12:00.355761+00:00 app[web.1]: at Authenticator.transformAuthInfo (/app/node_modules/passport/lib/authenticator.js:453:5)
2021-02-12T04:12:00.355762+00:00 app[web.1]: at /app/node_modules/passport/lib/middleware/authenticate.js:267:22
2021-02-12T04:12:00.355762+00:00 app[web.1]: at /app/node_modules/passport/lib/http/request.js:52:7

**Comment by keithschm** [comment]
Me too any idea?

**Comment by andrewjymoon** [comment]
https://github.com/rafael-carvalho/meraki-azure-ad/issues/2#issuecomment-1514539947
